services:
    cloth-app:
        build:
            context: .
            dockerfile: ./docker/dev.Dockerfile
        container_name: cloth-app
        env_file:
            - .env
        depends_on:
            database:
                condition: service_healthy
        volumes:
            - .:/app
        restart: always
        networks:
            - app-network
        ports:
            - 3000:3000

    database:
        container_name: postgres
        image: postgres:15
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'maindb']
            interval: 5s
            timeout: 10s
            retries: 5
        restart: always

networks:
    app-network:
        driver: bridge

volumes:
    postgres_data:
